# Generated by Django 5.0 on 2023-12-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_services_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('1', 'Qabul qilindi'), ('2', 'Bajarildi'), ('3', 'Bekor qilindi')], max_length=255),
        ),
    ]
