# Generated by Django 5.0 on 2023-12-08 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0003_alter_serviceorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='author',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='author_body',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='author_image',
            field=models.ImageField(default=1, upload_to='authors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='author_site',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
