# Generated by Django 5.0 on 2023-12-10 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0005_serviceorder_adress_serviceorder_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceorder',
            old_name='adress',
            new_name='address',
        ),
    ]
