# Generated by Django 5.0 on 2023-12-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0006_rename_adress_serviceorder_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('1', 'Qabul qilindi'), ('2', 'Bajarildi'), ('3', 'Bekor qilindi')], default='1', max_length=255),
        ),
    ]
