# Generated by Django 5.0 on 2023-12-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0007_alter_serviceorder_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name_plural': 'Servislar kategoriyalari'},
        ),
        migrations.AlterModelOptions(
            name='serviceorder',
            options={'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Barcha servislar'},
        ),
    ]
