# Generated by Django 5.0 on 2023-12-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default=2, upload_to='news'),
            preserve_default=False,
        ),
    ]
