# Generated by Django 5.0 on 2023-12-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cap_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
