# Generated by Django 5.0 on 2023-12-10 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_news_cap_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Yangiliklar'},
        ),
    ]
