# Generated by Django 5.0 on 2023-12-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=455)),
                ('icon', models.CharField(max_length=455)),
                ('count', models.CharField(max_length=255)),
                ('aniq', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HomeHamkor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='home-images')),
                ('link', models.CharField(max_length=455)),
            ],
        ),
        migrations.CreateModel(
            name='HomeIqtibos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=455)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSerives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=455)),
                ('icon', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('slug', models.CharField(max_length=455)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.TextField()),
                ('title_2', models.CharField(max_length=455)),
                ('title_3', models.CharField(max_length=455)),
                ('body', models.TextField()),
                ('image_1', models.ImageField(upload_to='home-images')),
                ('text_1', models.CharField(max_length=455)),
                ('image_2', models.ImageField(upload_to='home-images')),
                ('text_2', models.CharField(max_length=455)),
                ('image_3', models.ImageField(upload_to='home-images')),
                ('text_3', models.CharField(max_length=455)),
                ('image_4', models.ImageField(upload_to='home-images')),
                ('text_4', models.CharField(max_length=455)),
            ],
        ),
        migrations.CreateModel(
            name='HomeWelcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='home-images')),
                ('image2', models.ImageField(upload_to='home-images')),
                ('cap_title', models.CharField(max_length=455)),
                ('title', models.CharField(max_length=455)),
                ('body', models.TextField()),
                ('button_title', models.CharField(max_length=455)),
                ('button_link', models.CharField(max_length=455)),
            ],
        ),
    ]
