# Generated by Django 5.0 on 2023-12-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeserives',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
