# Generated by Django 5.0 on 2023-12-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_homeserives_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homestep',
            name='title_1',
        ),
        migrations.RemoveField(
            model_name='homestep',
            name='title_2',
        ),
        migrations.RemoveField(
            model_name='homestep',
            name='title_3',
        ),
        migrations.AddField(
            model_name='homestep',
            name='title',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
