# Generated by Django 5.0 on 2023-12-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_homestep_title_1_remove_homestep_title_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeserives',
            name='animation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
