# Generated by Django 5.0 on 2023-12-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_homeserives_animation'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeserives',
            name='animation_delay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
