# Generated by Django 5.0 on 2023-12-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_homeserives_animation_delay'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=455)),
                ('cap_title', models.CharField(max_length=455)),
                ('body', models.TextField()),
                ('adress', models.CharField(max_length=455)),
                ('phone', models.CharField(max_length=455)),
                ('email', models.CharField(max_length=455)),
            ],
        ),
        migrations.CreateModel(
            name='ContactRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=455)),
                ('phone', models.CharField(max_length=455)),
                ('message', models.TextField()),
            ],
        ),
    ]
