# Generated by Django 5.0 on 2023-12-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_contactinfo_contactrequests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name_plural': 'Kontakt sahifasi'},
        ),
        migrations.AlterModelOptions(
            name='contactrequests',
            options={'verbose_name_plural': 'Tizimga kelgan xabarlar'},
        ),
        migrations.AlterModelOptions(
            name='homecounter',
            options={'verbose_name_plural': 'Counter'},
        ),
        migrations.AlterModelOptions(
            name='homehamkor',
            options={'verbose_name_plural': 'Hamkorlar'},
        ),
        migrations.AlterModelOptions(
            name='homeiqtibos',
            options={'verbose_name_plural': 'Iqtibos'},
        ),
        migrations.AlterModelOptions(
            name='homeserives',
            options={'verbose_name_plural': 'Servislar'},
        ),
        migrations.AlterModelOptions(
            name='homestep',
            options={'verbose_name_plural': 'Bosqichlar'},
        ),
        migrations.AlterModelOptions(
            name='homewelcome',
            options={'verbose_name_plural': 'Hush kelibsiz'},
        ),
    ]
