# Generated by Django 5.0 on 2023-12-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_remove_twoheaderservices_service_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=455)),
                ('token', models.CharField(max_length=555)),
                ('user_id', models.CharField(max_length=255)),
            ],
        ),
    ]
