# Generated by Django 5.0 on 2023-12-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_telegrambotsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footeraddresinfo',
            options={'verbose_name_plural': 'Footer manzil sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='footerlinks',
            options={'verbose_name_plural': 'Footer linklar'},
        ),
        migrations.AlterModelOptions(
            name='footersettings',
            options={'verbose_name_plural': 'Footer sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='oneheader',
            options={'verbose_name_plural': 'Asosiy menyular'},
        ),
        migrations.AlterModelOptions(
            name='seosettings',
            options={'verbose_name_plural': 'Seo sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name_plural': 'Logo va title sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='socialnetworks',
            options={'verbose_name_plural': 'Ijtimoiy tarmoqlar'},
        ),
        migrations.AlterModelOptions(
            name='telegrambotsettings',
            options={'verbose_name_plural': 'Telegram bot sozlamalari'},
        ),
    ]
